### ISSUE TITLE
What should i do to success making this project?

### ISSUE THREAD

**Issue by xingbei437** [rpetrich/AppList#16]
I have Xcode5.0 as Xcode.app and Xcode4.6 as Xcode_Legacy.app.
Frist make error:
![2014-04-19 5 05 35](https://cloud.githubusercontent.com/assets/2703411/2748046/ea96c1f0-c7a1-11e3-9b1a-6b0fddcd3444.png)

a lot of similar error reporting ......

Then I remove the armv6 option for libapplist and make again, new error appears:
![2014-04-19 5 09 02](https://cloud.githubusercontent.com/assets/2703411/2748049/54ae17fa-c7a2-11e3-8d10-e1a0d3dc14c0.png)

And i discover that the SBApplication.h in your frame work requires DEPLOYMENT_TARGET=3.0, because:

#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_3_2
-(NSString*)pathForIcon;
-(NSString*)pathForSmallIcon;
-(id)spotlightIcons;
-(void)flushSnapshotsForAllRoles;
-(BOOL)isPrerenderedIcon;
-(void)_sendCurrentDeviceOrientation;
#endif

So, i was confused what should i do to build this project?

**Comment by rpetrich** [comment]
Closed as this issue is so old.
