### ISSUE TITLE
Create tags and releases for 1.5.8 and 1.5.9

### ISSUE THREAD

**Issue by kef** [rpetrich/AppList#22]
From the git log, I can see comments for official releases of 1.5.8 and 1.5.8. These haven't been tagged in git and the corresponding releases haven't been created on GitHub. This was done prior to that point. Is this just an oversight or has your release process changed?

Obviously not a big issue for anyone, since we can just check out the code at the appropriate git revision and get the header files corresponding to those releases.

**Comment by rpetrich** [comment]
An oversight. Thanks for reporting.
