### ISSUE TITLE
Deprecated method in iOS 8.

### ISSUE THREAD

**Issue by r-plus** [rpetrich/AppList#23]
`+[NSPropertyListSerialization propertyListFromData:mutabilityOption:format:errorDescription:]` method have been deprecated in iOS 8.
Use `propertyListWithData:options:format:error:` instead.

https://github.com/rpetrich/AppList/blob/master/ALApplicationList.m#L382
https://github.com/rpetrich/AppList/blob/master/ALApplicationList.m#L403

**Comment by rpetrich** [comment]
Yes, it's deprecated. Since AppList supports back to iPhoneOS 3.0, I need to use methods that have long been deprecated 😥
