### ISSUE TITLE
v1.5.12 - Crash When _displayIdentifiers is Empty

### ISSUE THREAD

**Issue by tateu** [rpetrich/AppList#26]
Using the exact same code in my tweak, libapplist.dylib crashes using v1.5.12 but does not crash using v1.5.11.

`*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'`

```
ALApplicationTableDataSource *_dataSource = [[ALApplicationTableDataSource alloc] init];
NSString *enabledList = @"";

_dataSource.sectionDescriptors = [NSArray arrayWithObjects:
		[NSDictionary dictionaryWithObjectsAndKeys:
			@"Enabled Applications", ALSectionDescriptorTitleKey,
			@"ALCheckCell", ALSectionDescriptorCellClassNameKey,
			iconSize, ALSectionDescriptorIconSizeKey,
			@YES, ALSectionDescriptorSuppressHiddenAppsKey,
			[NSString stringWithFormat:@"bundleIdentifier in {%@}", enabledList],
			ALSectionDescriptorPredicateKey
		, nil],

		[NSDictionary dictionaryWithObjectsAndKeys:
			@"Available Applications", ALSectionDescriptorTitleKey,
			@"ALCheckCell", ALSectionDescriptorCellClassNameKey,
			iconSize, ALSectionDescriptorIconSizeKey,
			@YES, ALSectionDescriptorSuppressHiddenAppsKey,
			[NSString stringWithFormat:@"not bundleIdentifier in {%@}", enabledList],
			ALSectionDescriptorPredicateKey
		, nil]
	 , nil];
```

It crashes in [updateIndexPath from ALApplicationTableDataSource.m](https://github.com/rpetrich/AppList/blob/master/ALApplicationTableDataSource.m#L317) because updateIndexPath is called when _displayIdentifiers is empty. In my code above, when enabledList is an empty string, the first section of _dataSource.sectionDescriptors is an empty array.

In v1.5.11, the equivalent method, [updateCell](https://github.com/rpetrich/AppList/blob/97bcf0fe0a4470b7015c579a8e7c7b07f294fc4c/ALApplicationTableDataSource.m#L317), does not ever get called when _displayIdentifiers is empty.

One simple way to fix it seems to be to change the if statement in updateIndexPath:
`if (_displayIdentifiers.count > 0 && [displayIdentifier isEqual:[_displayIdentifiers objectAtIndex:indexPath.row]] && newIconSize == iconSize) {`

Another way to fix it would be to figure out why updateIndexPath in v1.5.12 gets called with an empty _displayIdentifiers array but updateCell in v1.5.11 does not and keep it from happening.

**Comment by rpetrich** [comment]
Hurray for race conditions!

Fixed in master and in the next release due out soon.

**Comment by tateu** [comment]
Thanks

**Comment by rpetrich** [comment]
@tateu: To be 100% certain, could you try out this beta: https://rpetri.ch/db/applist_1.5.12-1_iphoneos-arm.deb (or the latest commit on master)

**Comment by tateu** [comment]
Yes, that deb file fixes it.

Josh

**Comment by tateu** [comment]
Is this going to be released anytime soon?

**Comment by rpetrich** [comment]
This is now released.

**Comment by tateu** [comment]
thanks
