### ISSUE TITLE
SpringBoard crash on iOS 13 when get large icon image by `+[SBIconModel sharedInstance]: unrecognized selector`

### ISSUE THREAD

**Issue by r-plus** [rpetrich/AppList#36]
SpringBoard crash on iOS 13 when get large icon image by `+[SBIconModel sharedInstance]: unrecognized selector`
https://github.com/rpetrich/AppList/blob/master/ALApplicationList.x#L577

### NOTE
No longer exist `SBIconViewMap` class in iOS 13.

https://github.com/rpetrich/AppList/blob/master/ALApplicationList.x#L568

### crash log

[applist_crash.txt](https://github.com/rpetrich/AppList/files/3964753/applist_crash.txt)

**Comment by willsmillie** [comment]
I have a user experiencing the same thing on 13.2.2, it's working fine for me though...

Were you able to figure anything out?

**Comment by r-plus** [comment]
I made fixing tweak for this issue https://github.com/r-plus/AppListFixer

**Comment by r-plus** [comment]
this issue is fixed in version 1.5.15.
thx.
